export { default as HeroSection } from "./HeroSection"
export { default as VideoSection } from "./VideoSection"
export { default as POTSection } from "./POTSection"
export { default as StakeSection } from "./StakeSection"
export { default as AboutSection } from "./AboutSection"
export { default as CollectionSection } from "./CollectionSection"
export { default as RoadmapSection } from "./RoadmapSection"
export { default as FAQSection } from "./FAQSection"
